server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}
spring:
  config:
    import: nacos:${spring.application.name}.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: ruoyu
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
    sentinel:
      transport:
        port: 8890
        dashboard: 127.0.0.1:8858
      eager: true
      filter:
        enabled: false #网关限流需要关闭
    gateway:
      routes:
        - id: ruoyu-order
          uri: lb://ruoyu-order
          predicates:
            - Path=/ruoyu-order/**
        - id: ruoyu-product
          uri: lb://ruoyu-product
          predicates:
            - Path=/ruoyu-product/**
        - id: ruoyu-user
          uri: lb://ruoyu-user
          predicates:
            - Path=/ruoyu-user/**
      default-filters:
        - AddRequestHeader=from, gateway
  application:
    name: ruoyu-gateway
