server:
  port: 8091
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: ruoyu-order
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: ruoyu
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
      compression:
        request:
          enabled: true
        response:
          enabled: true
    sentinel:
      transport:
        port: 8891
        dashboard: 127.0.0.1:8858
      eager: true
      datasource:
        ds-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            dataId: ${spring.application.name}-flow
            data_type: json
            rule-type: flow
        ds-degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            dataId: ${spring.application.name}-degrade
            data_type: json
            rule-type: degrade
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruoyu_order?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 600000
      connection-timeout: 30000
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:common-service.yml

# 开启feign熔断降级
feign:
  sentinel:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.npc.ruoyu.order.domain
  configuration:
    map-underscore-to-camel-case: true
